CREATE TABLE [dbo].[cdqm_customer_persistent](
	[CUSTOMER_PERSISTENT_ID] INT NOT NULL IDENTITY,
	[COD_CUST_ID] [numeric](10, 0) NULL,
	[BVN] [varchar](60) NOT NULL,
	[COD_ACCT_NO_DEFAULT] [varchar](16) NOT NULL,
	[DAT_CUST_OPEN] [varchar](10) NOT NULL,
	[FLG_STAFF] [varchar](1) NOT NULL,
	[FLG_LOC_GLOB] [varchar](1) NOT NULL,
	[COD_CC_HOMEBRN] [numeric](5, 0) NOT NULL,
	[NAM_CUST_SHRT] [varchar](60) NOT NULL,
	[NAM_CUST_FULL] [varchar](120) NOT NULL,
	[NAM_CUST_LAST] [varchar](60) NOT NULL,
	[NAM_CUST_MID] [varchar](60) NOT NULL,
	[NAM_CUST_FIRST] [varchar](60) NOT NULL,
	[TXT_PROFESS_CAT] [numeric](3, 0) NOT NULL,
	[TXT_CUSTADR_ADD1] [varchar](105) NOT NULL,
	[TXT_CUSTADR_ADD2] [varchar](105) NOT NULL,
	[TXT_CUSTADR_ADD3] [varchar](105) NOT NULL,
	[NAM_CUSTADR_CITY] [varchar](105) NOT NULL,
	[NAM_CUSTADR_STATE] [varchar](105) NOT NULL,
	[REF_CUST_PHONE] [varchar](45) NOT NULL,
	[REF_CUST_EMAIL] [varchar](120) NOT NULL,
	[DAT_BIRTH_CUST] [varchar](10) NOT NULL,
	[TXT_CUST_SEX] [varchar](1) NOT NULL,
	[COD_CUST_MARSTAT] [numeric](3, 0) NOT NULL,
	[NAM_CUST_SPOUSE] [varchar](120) NOT NULL,
	[TXT_SPOUSE_OCCPN] [varchar](120) NOT NULL,
	[CTR_DPNDT_CHLDRN] [numeric](3, 0) NOT NULL,
	[TXT_CUST_NATNLTY] [varchar](45) NOT NULL,
	[DAT_INCORPORATED] [varchar](10) NOT NULL,
	[COD_BUSINESS_REGNO] [varchar](45) NOT NULL,
	[TXT_CUST_RESIDENCE] [varchar](9) NOT NULL,
	[DAT_LAST_MNT] [varchar](10) NOT NULL,
	[MIS_CODE] [varchar](500) NOT NULL,
	[RM_CODE] [varchar](350) NOT NULL,
	[RM_NAME] [varchar](350) NOT NULL,
	[PRODUCT_CODE] [varchar](500) NOT NULL,
	[PRODUCT_NAME] [varchar](150) NOT NULL,
	[IS_CARDABLE] [int] NOT NULL,
	[BUSINESS_DIVISION] [varchar](8000) NOT NULL,
	[CUSTOMER_SEGMENT] [varchar](15) NOT NULL,
	[CUSTOMER_SUB_SEGMENT] [varchar](50) NOT NULL,
	[PRODUCT_SEGMENT] [varchar](50) NOT NULL,
	[IS_CARDHOLDER] [int] NULL,
	[HAS_INTERNETBANKING] [int] NULL,
	[HAS_MOBILEBANKING] [int] NULL,
	[CREDIT_RATING] [varchar](100) NOT NULL,
	[CBN_SECTOR] [varchar](100) NOT NULL,
	[CBN_SUB_SECTOR] [varchar](100) NOT NULL,
	[AGE] [int] NULL,
	[AMOUNT] [money] NULL,
	[TRANS_COUNT] [int] NULL,
	[ACCOUNTCOUNT] [int] NULL,
	[IS_MERCHANTABLE] [int] NOT NULL,
	[IS_MERCHANT] [int] NOT NULL,
	[CUSTOMER_TYPE] [varchar](10) NULL,
	[MAXIMUM_AGE] [decimal](38, 0) NULL,
	[MINIMUM_AGE] [decimal](38, 0) NULL,
	[PRODUCTSTATUS] [int] NOT NULL,
	[CUST_FULL_NAME_TITLE] [varchar](376) NULL,
	[cust_birthdate_status] [varchar](38) NULL,
	[PRODUCT_STATUS] [varchar](7) NULL,
	[CUST_FULL_ADDRESS] [varchar](8000) NULL,
	[DERIVED_STATE] [varchar](255) NULL,
	[Postacode] [varchar](255) NULL,
	[LGA] [varchar](255) NULL,
	[NAM_CUSTADR_CNTRY] [varchar](255) NULL,
	[country_status] [varchar](9) NULL,
	[email_status] [varchar](38) NULL,
	[gender_status] [varchar](7) NULL,
	[TXT_CUST_PREFIX] [varchar](255) NULL,
	[prefix_status] [varchar](9) NULL,
	[DERIVED_GENDER] [varchar](255) NULL,
	[COD_GROUP_ID] [numeric](10, 0) NULL,
	[_key_in] [int] NULL,
	[_key_out] [int] NULL,
	[_score] [real] NULL,
	[NAM_CUST_FULL_clean] [varchar](120) NULL,
	[DAT_BIRTH_CUST_clean] [varchar](10) NULL,
	[TXT_CUST_SEX_clean] [varchar](1) NULL,
	[_Similarity_NAM_CUST_FULL] [real] NULL,
	[CustomerMiscode] [varchar](50) NULL,
	[LoadDate] [datetime] NOT NULL,
	[IsGolden] [bit] NOT NULL,
	[Active] BIT NULL, 
    [Deleted] BIT NULL, 
    [CreatedBy] VARCHAR(50) NULL, 
    [CreatedOn] DATETIME NULL, 
    [UpdatedBy] VARCHAR(50) NULL, 
    [UpdatedOn] DATETIME NULL, 
    [RowVersion] TIMESTAMP NOT NULL,
    CONSTRAINT [PK_cdqm_customer_persistent] PRIMARY KEY ([CUSTOMER_PERSISTENT_ID]) 
)

GO
