CREATE TABLE [dbo].[cdqm_merchant]
(
	[MerchantId] INT NOT NULL IDENTITY,
	[SN]  varchar(255) NULL,
	[BranchName] varchar(255)  NULL,
	[AccountOfficerCode]  VARCHAR(255)  NULL,
	[TeamCode]  VARCHAR(255)  NULL,
	[SBU]  VARCHAR(255)  NULL,
	[MerchantCode]  VARCHAR(255)  NULL,
	[MerchantName]  VARCHAR(255)  NULL,
	[ContactTitle]  VARCHAR(255)  NULL,
	[ContactName]  VARCHAR(255)  NULL,
	[MobilePhone]  VARCHAR(255)  NULL,
	[Email]  VARCHAR(255)  NULL,
	[PhysicalAddr]  VARCHAR(255)  NULL,
	[TerminalID]  VARCHAR(255)  NULL,
	[BankCode]  VARCHAR(255)  NULL,
	[BankAccNo]  VARCHAR(255)  NULL,
	[BankAccType]  VARCHAR(255)  NULL,
	[BusinessOccupationCode]  VARCHAR(255)  NULL,
	[MerchantCategoryCode]  VARCHAR(255)  NULL,
	[StateCode]  VARCHAR(255)  NULL,
	[VisaAcquireIDNumber]  VARCHAR(255)  NULL,
	[VerveAcquireIDNumber]  VARCHAR(255)  NULL,
	[MasterCardAcquireIDNumber]  VARCHAR(255)  NULL,
	[TerminalOwnerCode]  VARCHAR(255)  NULL,
	[LGALCDA]  VARCHAR(255)  NULL,
	[PTASP]  VARCHAR(255)  NULL,
    [Active] BIT NULL DEFAULT 1, 
    [Deleted] BIT NULL DEFAULT 0, 
    [CreatedBy] VARCHAR(50) NULL, 
    [CreatedOn] DATETIME NULL, 
    [UpdatedBy] VARCHAR(50) NULL, 
    [UpdatedOn] DATETIME NULL, 
    [RowVersion] TIMESTAMP NOT NULL, 
    CONSTRAINT [PK_cdqm_merchant] PRIMARY KEY ([MerchantId]) 
)

GO
