CREATE TABLE [dbo].[bud_staff_count]
(
	[StaffCountId] INT NOT NULL IDENTITY, 
	[DefinitionCode] VARCHAR(50) NOT NULL,
	[MisCode] VARCHAR(50) NOT NULL,  
    [GradeCode] VARCHAR(50) NOT NULL, 
    [ClassificationCode] VARCHAR(50) NOT NULL, 
	[Month1] decimal(18,4) Not  NULL, 
	[Month2] decimal(18,4) Not  NULL, 
	[Month3] decimal(18,4) Not  NULL, 
	[Month4] decimal(18,4) Not  NULL, 
	[Month5] decimal(18,4) Not  NULL, 
	[Month6] decimal(18,4) Not  NULL, 
	[Month7] decimal(18,4) Not  NULL, 
	[Month8] decimal(18,4) Not  NULL, 
	[Month9] decimal(18,4) Not  NULL, 
	[Month10] decimal(18,4) Not  NULL, 
	[Month11] decimal(18,4) Not  NULL, 
	[Month12] decimal(18,4) Not  NULL,
	[CurrencyCode] VARCHAR(10) NOT NULL, 
	[Type] INT NOT NULL, 
	[Center] INT NOT NULL,
	[Year] VARCHAR(50) NOT NULL, 
	[Active] BIT NULL DEFAULT 1, 
    [Deleted] BIT NULL DEFAULT 0, 
    [CreatedBy] VARCHAR(50) NULL, 
    [CreatedOn] DATETIME NULL, 
    [UpdatedBy] VARCHAR(50) NULL, 
    [UpdatedOn] DATETIME NULL, 
    [RowVersion] TIMESTAMP NOT NULL, 
    CONSTRAINT [PK_bud_staff_count] PRIMARY KEY ([StaffCountId]), 
    CONSTRAINT [AK_bud_staff_count] UNIQUE ([DefinitionCode],[MisCode],[GradeCode],[ClassificationCode],[Year]) 
)
