CREATE TABLE [dbo].[mpr_opex_depnxmpt](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BRANCHCODE] [varchar](100) NULL,
	[CompanyCode] varchar(10) NULL
 CONSTRAINT [PK_mpr_opex_depnxmpt] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]