//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fintrak.Presentation.CloudClient.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool IsDemo { get; set; }
        public Nullable<System.DateTime> DemoStartDate { get; set; }
        public Nullable<System.DateTime> DemoEndDate { get; set; }
        public int DemoDuration { get; set; }
        public bool IsActivated { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public string Message { get; set; }
    }
}
